<script setup>
import { computed, nextTick, ref } from 'vue'

const instructionModules = import.meta.glob(
  '../../../my_eccv/pred_vs_gt/*/instruction.txt',
  {
    eager: true,
    import: 'default',
    query: '?raw',
  }
)

const videoModules = import.meta.glob(
  '../../../my_eccv/pred_vs_gt/*/*.mp4',
  {
    eager: true,
    import: 'default',
  }
)

const getFolderName = (path) => {
  const matched = path.match(/pred_vs_gt\/([^/]+)\//)
  return matched ? matched[1] : ''
}

const extractPrompt = (rawText = '') => {
  const promptLine = rawText
    .split(/\r?\n/)
    .find((line) => line.trim().toLowerCase().startsWith('prompt:'))

  return promptLine
    ? promptLine.replace(/^prompt:\s*/i, '').trim()
    : 'Prompt unavailable.'
}

const taskOrder = [
  'task_obstacle0',
  'task_building',
  'task_0',
  'task_road',
  'task_farm',
  'task_obstacle1',
  'task_hl',
  'task_orbit',
  'task_orbit_multi',
]

const discoveredFolders = Object.keys(instructionModules)
  .map((path) => getFolderName(path))
  .filter(Boolean)

const folders = [
  ...taskOrder.filter((folder) => discoveredFolders.includes(folder)),
  ...discoveredFolders.filter((folder) => !taskOrder.includes(folder)).sort((a, b) => a.localeCompare(b)),
]

const tasks = folders
  .map((folder) => {
    const instructionEntry = Object.entries(instructionModules).find(([path]) =>
      path.includes(`/pred_vs_gt/${folder}/instruction.txt`)
    )

    const videoEntry = Object.entries(videoModules).find(([path]) =>
      path.includes(`/pred_vs_gt/${folder}/gt_pred_side_by_side_with_traj.mp4`)
    )

    return {
      key: folder,
      prompt: extractPrompt(instructionEntry?.[1]),
      videoSrc: videoEntry?.[1] ?? '',
    }
  })
  .filter((task) => task.videoSrc)

const noteBackgrounds = [
  '#c5e9e3',
  '#c5e9e3',
  '#c5e9e3',
  '#d7e1eb',
  '#d7e1eb',
  '#d7e1eb',
  '#f2dada',
  '#f2dada',
  '#f2dada',
]

const noteRotations = ['-2deg', '1.5deg', '-1deg', '2deg', '-1.5deg', '1deg', '-1deg', '1.5deg', '-2deg']

const styledTasks = tasks.map((task, index) => ({
  ...task,
  noteStyle: {
    '--note-bg': noteBackgrounds[index % noteBackgrounds.length],
    '--note-rotate': noteRotations[index % noteRotations.length],
  },
}))

const selectedTaskKey = ref('')
const playbackHint = ref('Click a prompt note to start the rollout playback.')
const rolloutVideoRef = ref(null)

const selectedTask = computed(
  () => styledTasks.find((task) => task.key === selectedTaskKey.value) ?? null
)

const selectTask = async (task) => {
  selectedTaskKey.value = task.key
  playbackHint.value = 'Playing rollout...'

  await nextTick()

  const video = rolloutVideoRef.value
  if (!video) {
    return
  }

  try {
    video.pause()
  } catch (error) {
    console.warn('Unable to pause previous playback.', error)
  }

  try {
    video.currentTime = 0
  } catch (error) {
    console.warn('Unable to reset video time.', error)
  }

  try {
    video.load()
    const playPromise = video.play()
    if (playPromise && typeof playPromise.then === 'function') {
      await playPromise
    }
    playbackHint.value = 'Playing rollout...'
  } catch (error) {
    console.warn('Autoplay was blocked.', error)
    playbackHint.value = 'Playing rollout...'
  }
}

const handleVideoPlay = () => {
  playbackHint.value = 'Playing rollout...'
}

const handleVideoEnded = () => {
  playbackHint.value = 'Finished.'
}
</script>

<template>
  <section class="more-visualization-section">
    <el-divider />

    <el-row justify="center">
      <h1 class="section-title">Fly Your Embodied UAV in a Digital Twin World!</h1>
    </el-row>

    <el-row justify="center">
      <el-col :xs="22" :sm="20" :md="18" :lg="16" :xl="14">
        <p class="section-description">
          We present successful rollout cases of UAV HL-VLA tasks generated by the Pi0 model. Click a prompt note to
          play the corresponding rollout.
        </p>

        <div class="prompt-grid">
          <button
            v-for="(task, index) in styledTasks"
            :key="task.key"
            class="prompt-note"
            :class="{ 'is-active': selectedTaskKey === task.key }"
            :style="task.noteStyle"
            type="button"
            @click="selectTask(task)"
          >
            <span class="note-index">Prompt {{ index + 1 }}</span>
            <span class="note-text">{{ task.prompt }}</span>
          </button>
        </div>

        <article v-if="selectedTask" class="task-card">
          <p class="task-prompt">
            <span class="prompt-label">Prompt:</span>
            {{ selectedTask.prompt }}
          </p>

          <p class="playback-hint">{{ playbackHint }}</p>

          <div class="task-video-block">
            <video
              ref="rolloutVideoRef"
              :key="selectedTask.key"
              class="task-video"
              :src="selectedTask.videoSrc"
              controls
              playsinline
              preload="metadata"
              @play="handleVideoPlay"
              @ended="handleVideoEnded"
            />

            <div class="task-video-labels">
              <p class="video-label">Ground Truth</p>
              <p class="video-label">Prediction by Pi0</p>
              <p class="video-label">Trajectory</p>
            </div>
          </div>
        </article>

        <div v-else class="selection-placeholder">
          <p class="placeholder-title">Select A Prompt</p>
          <p class="placeholder-text">Choose one of the prompt notes above to start the rollout playback.</p>
        </div>

      </el-col>
    </el-row>
  </section>
</template>

<style scoped>
.section-description {
  margin: 8px 0 0;
  font-size: 16px;
  line-height: 1.7;
  text-align: center;
}

.prompt-grid {
  margin-top: 24px;
  display: grid;
  grid-template-columns: repeat(3, minmax(0, 1fr));
  gap: 12px;
}

.prompt-note {
  position: relative;
  min-height: 110px;
  padding: 14px 13px 12px;
  border: none;
  border-radius: 10px 14px 12px 10px;
  background: var(--note-bg);
  box-shadow: 0 12px 22px rgba(0, 0, 0, 0.14);
  text-align: left;
  cursor: pointer;
  transform: rotate(var(--note-rotate));
  transition: transform 0.2s ease, box-shadow 0.2s ease;
}

.prompt-note::before {
  content: '';
  position: absolute;
  top: 10px;
  right: 12px;
  width: 15px;
  height: 15px;
  border-radius: 50%;
  background: rgba(255, 255, 255, 0.72);
  box-shadow: inset 0 1px 2px rgba(255, 255, 255, 0.7), 0 2px 5px rgba(0, 0, 0, 0.12);
}

.prompt-note:hover {
  transform: rotate(var(--note-rotate)) translateY(-3px);
  box-shadow: 0 16px 28px rgba(0, 0, 0, 0.16);
}

.prompt-note.is-active {
  outline: 2px solid #2f3944;
  transform: rotate(var(--note-rotate)) translateY(-4px);
}

.note-index {
  display: block;
  margin-bottom: 8px;
  font-family: "MyFont", Georgia, serif;
  font-size: 11px;
  font-weight: 800;
  letter-spacing: 0.08em;
  text-transform: uppercase;
  color: rgba(42, 52, 64, 0.72);
}

.note-text {
  display: -webkit-box;
  overflow: hidden;
  font-family: "MyFont", Georgia, serif;
  color: #27313b;
  font-size: 13px;
  font-weight: 700;
  line-height: 1.35;
  -webkit-box-orient: vertical;
  -webkit-line-clamp: 4;
}

.task-card {
  margin-top: 18px;
  padding: 22px;
  border-radius: 18px;
  background: #fafafa;
  box-shadow: 0 8px 24px rgba(0, 0, 0, 0.08);
}

.task-prompt {
  margin: 0 0 16px;
  font-size: 16px;
  line-height: 1.7;
  text-align: left;
}

.playback-hint {
  margin: 0 0 18px;
  font-size: 14px;
  line-height: 1.6;
  color: #55616d;
}

.prompt-label {
  font-weight: 700;
  margin-right: 6px;
}

.task-video-block {
  width: 100%;
  position: relative;
}

.task-video {
  width: 100%;
  height: 300px;
  display: block;
  border-radius: 12px;
  box-shadow: 0 8px 24px rgba(0, 0, 0, 0.12);
  background: #000;
  object-fit: contain;
  object-position: center;
}

.task-video-labels {
  display: grid;
  grid-template-columns: repeat(3, minmax(0, 1fr));
  margin-top: 10px;
  padding: 0 18px;
}

.video-label {
  margin: 0;
  color: #1f1f1f;
  font-size: 15px;
  font-weight: 600;
  text-align: center;
}

.selection-placeholder {
  width: 100%;
  min-height: 300px;
  padding: 26px 22px;
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  border-radius: 12px;
  border: 2px dashed #c6ced6;
  background: linear-gradient(180deg, #fbfcfd 0%, #f3f6f8 100%);
  text-align: center;
  box-sizing: border-box;
}

.selection-placeholder {
  margin-top: 18px;
}

.placeholder-title {
  margin: 0 0 8px;
  font-size: 18px;
  font-weight: 700;
  color: #2d3742;
}

.placeholder-text {
  margin: 0;
  max-width: 360px;
  font-size: 15px;
  line-height: 1.7;
  color: #5f6b76;
}

@media (max-width: 900px) {
  .prompt-grid {
    grid-template-columns: 1fr 1fr;
  }

  .task-video,
  .selection-placeholder {
    width: 100%;
    height: 220px;
  }

  .task-video-labels {
    padding: 0 12px;
  }
}

@media (max-width: 640px) {
  .prompt-grid {
    grid-template-columns: 1fr;
  }
}
</style>
