<script setup>
import { computed, ref } from 'vue'

const instructionModules = import.meta.glob(
  '../../../my_eccv/pred_vs_gt/*/instruction.txt',
  {
    eager: true,
    import: 'default',
    query: '?raw',
  }
)

const imageModules = import.meta.glob(
  '../../../my_eccv/pred_vs_gt/*/*.png',
  {
    eager: true,
    import: 'default',
  }
)

const videoModules = import.meta.glob(
  '../../../my_eccv/pred_vs_gt/*/*.mp4',
  {
    eager: true,
    import: 'default',
  }
)

const getFolderName = (path) => {
  const matched = path.match(/pred_vs_gt\/([^/]+)\//)
  return matched ? matched[1] : ''
}

const extractPrompt = (rawText = '') => {
  const promptLine = rawText
    .split(/\r?\n/)
    .find((line) => line.trim().toLowerCase().startsWith('prompt:'))

  return promptLine
    ? promptLine.replace(/^prompt:\s*/i, '').trim()
    : 'Prompt unavailable.'
}

const taskOrder = [
  'task_obstacle0',
  'task_building',
  'task_0',
  'task_road',
  'task_farm',
  'task_obstacle1',
  'task_hl',
  'task_orbit',
  'task_orbit_multi',
]

const discoveredFolders = Object.keys(instructionModules)
  .map((path) => getFolderName(path))
  .filter(Boolean)

const folders = [
  ...taskOrder.filter((folder) => discoveredFolders.includes(folder)),
  ...discoveredFolders.filter((folder) => !taskOrder.includes(folder)).sort((a, b) => a.localeCompare(b)),
]

const tasks = folders
  .map((folder) => {
    const instructionEntry = Object.entries(instructionModules).find(([path]) =>
      path.includes(`/pred_vs_gt/${folder}/instruction.txt`)
    )

    const imageEntry = Object.entries(imageModules).find(([path]) =>
      path.includes(`/pred_vs_gt/${folder}/`)
    )

    const videoEntry = Object.entries(videoModules).find(([path]) =>
      path.includes(`/pred_vs_gt/${folder}/`)
    )

    return {
      key: folder,
      prompt: extractPrompt(instructionEntry?.[1]),
      imageSrc: imageEntry?.[1] ?? '',
      videoSrc: videoEntry?.[1] ?? '',
    }
  })
  .filter((task) => task.imageSrc && task.videoSrc)

const visibleCount = ref(2)

const visibleTasks = computed(() => tasks.slice(0, visibleCount.value))
const hasMore = computed(() => visibleCount.value < tasks.length)

const loadMore = () => {
  visibleCount.value = Math.min(visibleCount.value + 2, tasks.length)
}
</script>

<template>
  <section class="more-visualization-section">
    <el-divider />

    <el-row justify="center">
      <h1 class="section-title">More Visualization</h1>
    </el-row>

    <el-row justify="center">
      <el-col :xs="22" :sm="20" :md="18" :lg="16" :xl="14">
        <p class="section-description">
          We present successful rollout cases of UAV HL-VLA tasks generated by the Pi0 model.
        </p>

        <div class="task-list">
          <article v-for="task in visibleTasks" :key="task.key" class="task-card">
            <p class="task-prompt">
              <span class="prompt-label">Prompt:</span>
              {{ task.prompt }}
            </p>

            <div class="task-media">
              <div class="task-video-block">
                <video
                  class="task-video"
                  :src="task.videoSrc"
                  controls
                  playsinline
                  preload="metadata"
                />

                <div class="task-video-labels">
                  <p class="video-label">Ground Truth</p>
                  <p class="video-label">Prediction</p>
                </div>
              </div>

              <img
                class="task-image"
                :src="task.imageSrc"
                :alt="`Visualization for ${task.key}`"
              />
            </div>
          </article>
        </div>

        <el-row v-if="hasMore" justify="center" class="load-more-row">
          <el-button round size="large" class="load-more-button" @click="loadMore">Load More</el-button>
        </el-row>
      </el-col>
    </el-row>
  </section>
</template>

<style scoped>
.section-description {
  margin: 8px 0 0;
  font-size: 16px;
  line-height: 1.7;
  text-align: center;
}

.task-list {
  margin-top: 28px;
  display: flex;
  flex-direction: column;
  gap: 28px;
}

.task-card {
  padding: 22px;
  border-radius: 18px;
  background: #fafafa;
  box-shadow: 0 8px 24px rgba(0, 0, 0, 0.08);
}

.task-prompt {
  margin: 0 0 16px;
  font-size: 16px;
  line-height: 1.7;
  text-align: left;
}

.prompt-label {
  font-weight: 700;
  margin-right: 6px;
}

.task-media {
  display: grid;
  grid-template-columns: minmax(0, 1.35fr) minmax(0, 0.75fr);
  gap: 18px;
  align-items: center;
}

.task-video-block {
  width: 100%;
  position: relative;
}

.task-video {
  width: 100%;
  height: 300px;
  display: block;
  border-radius: 12px;
  box-shadow: 0 8px 24px rgba(0, 0, 0, 0.12);
  background: #000;
  object-fit: contain;
  object-position: center;
}

.task-video-labels {
  position: absolute;
  left: 0;
  right: 0;
  bottom: 34px;
  display: grid;
  grid-template-columns: repeat(2, minmax(0, 1fr));
  padding: 0 18px;
  pointer-events: none;
}

.video-label {
  margin: 0;
  color: #fff;
  font-size: 15px;
  font-weight: 600;
  text-align: center;
  text-shadow: 0 2px 8px rgba(0, 0, 0, 0.9);
}

.task-image {
  width: 88%;
  height: 300px;
  display: block;
  justify-self: end;
  border-radius: 12px;
  box-shadow: 0 8px 24px rgba(0, 0, 0, 0.12);
  background: #fff;
  object-fit: contain;
  object-position: center;
}

.load-more-row {
  margin-top: 28px;
}

.load-more-button {
  min-height: 54px;
  padding: 0 34px;
  font-size: 17px;
}

@media (max-width: 900px) {
  .task-media {
    grid-template-columns: 1fr;
  }

  .task-video,
  .task-image {
    width: 100%;
    height: 220px;
  }

  .task-video-labels {
    bottom: 32px;
    padding: 0 12px;
  }
}
</style>
